import React, { useState } from 'react';
import { FileDown, FileText, Download, Printer, X, Check, Loader2 } from 'lucide-react';
import { api } from '../services/api';

interface ExportReportModalProps {
  investigationId: string;
  onClose: () => void;
}

export const ExportReportModal: React.FC<ExportReportModalProps> = ({ investigationId, onClose }) => {
  const [downloading, setDownloading] = useState<string | null>(null);
  const [copiedTicket, setCopiedTicket] = useState(false);

  const handleCopyTicket = async () => {
    try {
      const data = await api.getReportData(investigationId);
      const inv = data.investigation || {};
      const email = data.email || {};
      const iocs = (data.iocs || []).slice(0, 8);

      const ticketText = `*SECURITY INCIDENT DOSSIER - MAILTRACE AI*
--------------------------------------------------
Incident ID: ${investigationId}
Classification: ${inv.threat_type || 'PHISHING'}
Severity: ${inv.severity || 'HIGH'} (Risk Score: ${inv.risk_score || 0}/100)
Confidence: ${inv.confidence || 90}%

*Email Artifact*:
- Subject: ${email.subject || 'Unknown'}
- Sender: "${email.from_name || ''}" <${email.from_address || ''}>
- Date: ${email.date || new Date().toISOString()}
- Evidentiary SHA-256: ${email.raw_eml_sha256 || 'N/A'}

*Extracted IOCs*:
${iocs.map((i: any) => `- [${i.type}] ${i.indicator} (Risk: ${i.risk_level})`).join('\n')}

*Recommended SOC Containment*:
1. Quarantine email from all recipient mailboxes across tenant.
2. Ingest domain/IP into perimeter firewall and EDR blocklists.
3. Reset credentials if recipient entered password on landing page.
4. Notify SOC lead for forensic chain-of-custody archive.
--------------------------------------------------
Generated by MailTrace AI Forensic Intelligence Platform`;

      navigator.clipboard.writeText(ticketText);
      setCopiedTicket(true);
      setTimeout(() => setCopiedTicket(false), 2500);
    } catch (err: any) {
      alert(`Failed to format ticket: ${err.message}`);
    }
  };

  const handleDownloadPdf = async () => {
    setDownloading('pdf');
    try {
      const blob = await api.downloadReportPdf(investigationId);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `MailTrace-Report-${investigationId.slice(0, 8)}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      a.remove();
    } catch (err: any) {
      alert(`PDF download failed: ${err.message}`);
    } finally {
      setDownloading(null);
    }
  };

  const handleDownloadCsv = async () => {
    setDownloading('csv');
    try {
      const blob = await api.downloadIocsCsv(investigationId);
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `MailTrace-IOCs-${investigationId.slice(0, 8)}.csv`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      a.remove();
    } catch (err: any) {
      alert(`CSV download failed: ${err.message}`);
    } finally {
      setDownloading(null);
    }
  };

  const handleDownloadJson = async () => {
    setDownloading('json');
    try {
      const data = await api.getReportData(investigationId);
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `MailTrace-Dossier-${investigationId.slice(0, 8)}.json`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      a.remove();
    } catch (err: any) {
      alert(`JSON export failed: ${err.message}`);
    } finally {
      setDownloading(null);
    }
  };

  return (
    <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-white border border-slate-200 rounded-2xl max-w-md w-full shadow-2xl p-6 space-y-5 animate-in zoom-in-95">
        <div className="flex items-center justify-between border-b border-slate-200 pb-3">
          <div className="flex items-center space-x-2">
            <FileDown className="w-5 h-5 text-emerald-600" />
            <h3 className="font-mono text-sm font-bold text-slate-900 uppercase">
              Export Forensic Intelligence Report
            </h3>
          </div>
          <button onClick={onClose} className="p-1 hover:text-slate-800 text-slate-400 font-bold">
            <X className="w-5 h-5" />
          </button>
        </div>

        <p className="text-xs text-slate-600">
          Generate an evidentiary forensic artifact containing email headers, cryptographic authentication proofs, IOC tables, and AI classification storylines.
        </p>

        {/* Options */}
        <div className="space-y-3">
          {/* PDF Export */}
          <button
            onClick={handleDownloadPdf}
            disabled={Boolean(downloading)}
            className="w-full p-3.5 rounded-xl bg-slate-50 hover:bg-emerald-50/50 border border-slate-200 hover:border-emerald-400 text-left flex items-center justify-between group transition-all"
          >
            <div className="flex items-center space-x-3">
              <div className="p-2 rounded-lg bg-red-100 text-red-700 border border-red-200">
                <FileText className="w-5 h-5" />
              </div>
              <div>
                <h4 className="text-xs font-bold text-slate-900 group-hover:text-emerald-700 transition-colors">
                  Formal PDF Forensic Dossier
                </h4>
                <p className="text-[11px] text-slate-500">
                  Multi-page SOC forensic brief with executive summary & IOCs
                </p>
              </div>
            </div>
            {downloading === 'pdf' ? (
              <Loader2 className="w-4 h-4 text-emerald-600 animate-spin" />
            ) : (
              <Download className="w-4 h-4 text-slate-400 group-hover:text-emerald-600" />
            )}
          </button>

          {/* JSON Export */}
          <button
            onClick={handleDownloadJson}
            disabled={Boolean(downloading)}
            className="w-full p-3.5 rounded-xl bg-slate-50 hover:bg-emerald-50/50 border border-slate-200 hover:border-emerald-400 text-left flex items-center justify-between group transition-all"
          >
            <div className="flex items-center space-x-3">
              <div className="p-2 rounded-lg bg-emerald-100 text-emerald-800 border border-emerald-200">
                <FileDown className="w-5 h-5" />
              </div>
              <div>
                <h4 className="text-xs font-bold text-slate-900 group-hover:text-emerald-700 transition-colors">
                  Structured JSON Telemetry Dossier
                </h4>
                <p className="text-[11px] text-slate-500">
                  Full machine-readable export for SIEM / SOAR ingestion
                </p>
              </div>
            </div>
            {downloading === 'json' ? (
              <Loader2 className="w-4 h-4 text-emerald-600 animate-spin" />
            ) : (
              <Download className="w-4 h-4 text-slate-400 group-hover:text-emerald-600" />
            )}
          </button>

          {/* CSV IOC Export */}
          <button
            onClick={handleDownloadCsv}
            disabled={Boolean(downloading)}
            className="w-full p-3.5 rounded-xl bg-slate-50 hover:bg-emerald-50/50 border border-slate-200 hover:border-emerald-400 text-left flex items-center justify-between group transition-all"
          >
            <div className="flex items-center space-x-3">
              <div className="p-2 rounded-lg bg-emerald-100 text-emerald-800 border border-emerald-200">
                <Download className="w-5 h-5" />
              </div>
              <div>
                <h4 className="text-xs font-bold text-slate-900 group-hover:text-emerald-700 transition-colors">
                  CSV Indicators of Compromise (IOCs)
                </h4>
                <p className="text-[11px] text-slate-500">
                  Spreadsheet table ready for firewall and EDR blocklists
                </p>
              </div>
            </div>
            {downloading === 'csv' ? (
              <Loader2 className="w-4 h-4 text-emerald-600 animate-spin" />
            ) : (
              <Download className="w-4 h-4 text-slate-400 group-hover:text-emerald-600" />
            )}
          </button>

          {/* Copy Jira / ServiceNow Ticket */}
          <button
            onClick={handleCopyTicket}
            className="w-full p-3.5 rounded-xl bg-slate-50 dark:bg-slate-800/80 hover:bg-emerald-50/50 dark:hover:bg-emerald-950/40 border border-slate-200 dark:border-slate-700 hover:border-emerald-400 text-left flex items-center justify-between group transition-all"
          >
            <div className="flex items-center space-x-3">
              <div className="p-2 rounded-lg bg-purple-100 dark:bg-purple-900/60 text-purple-800 dark:text-purple-300 border border-purple-200 dark:border-purple-800">
                <FileText className="w-5 h-5" />
              </div>
              <div>
                <h4 className="text-xs font-bold text-slate-900 dark:text-slate-100 group-hover:text-emerald-700 dark:group-hover:text-emerald-400 transition-colors">
                  Copy Jira / ServiceNow Incident Ticket
                </h4>
                <p className="text-[11px] text-slate-500 dark:text-slate-400">
                  Formatted markdown brief with telemetry & containment steps
                </p>
              </div>
            </div>
            <span className="text-xs font-mono font-bold text-emerald-700 dark:text-emerald-400">
              {copiedTicket ? '✓ Copied!' : 'Copy'}
            </span>
          </button>

          {/* Print View */}
          <button
            onClick={() => window.print()}
            className="w-full p-3 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 border border-slate-200 dark:border-slate-700 text-xs font-mono font-bold text-slate-800 dark:text-slate-200 flex items-center justify-center space-x-2 transition-colors"
          >
            <Printer className="w-4 h-4 text-slate-600 dark:text-slate-400" />
            <span>Open Browser Print / Save as PDF</span>
          </button>
        </div>
      </div>
    </div>
  );
};
